accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name='accounts'
urlpatterns=[
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('signup_success/',views.SignUpSuccessView.as_view(),name='signup_success'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html', next_page='oharaapp:index'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

kadaiproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('oharaapp.urls')),
    path('',include('accounts.urls')),
]

oharaapp/urls.py
from django.urls import path
from . import views
from .views import TokutenView
from .views import Tokuten_post_List,Post_success,MypageView
app_name='oharaapp'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('tokuten/', TokutenView.as_view(), name='tokuten'),
    path('detail/', Tokuten_post_List.as_view(), name='detail'),  
    path('post_success/', Post_success.as_view(), name='post_success'),  
    path('mypage/', MypageView.as_view(), name='mypage'),  
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

oharaapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from accounts.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator

class Tokuten_post(models.Model):
    user=models.ForeignKey(CustomUser,verbose_name='ユーザー',on_delete=models.CASCADE)
    subject=models.CharField(verbose_name='科目',max_length=100)
    num=models.IntegerField(verbose_name='点数',validators=[
            MinValueValidator(0),
            MaxValueValidator(100)
        ])
    posted_at=models.DateTimeField(verbose_name='投稿日時',auto_now_add=True)
    def __str__(self):
        return self.subject

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=CustomUser
        # デフォルトでusername,password1,password2(emailも追加)
        fields=('username','email','password1','password2')

oharaapp/forms.py
from django.forms import ModelForm
from .models import Tokuten_post

class TokutenForm(ModelForm):
    class Meta:
        model = Tokuten_post
        fields = ['subject', 'num']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView,TemplateView
from django.contrib.auth import views as auth_views
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    form_class=CustomUserCreationForm
    template_name='signup.html'
    success_url=reverse_lazy('accounts:signup_success')
    def form_valid(self, form):
        user=form.save()
        self.object=user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name='signup_success.html'

oharaapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView,TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .models import Tokuten_post
from .forms import TokutenForm
from .models import Tokuten_post
from django.views.generic import ListView

class IndexView(TemplateView):
    template_name='index.html'

class Post_success(TemplateView):
    template_name='post_success.html'

class MypageView(TemplateView):
    template_name = 'mypage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        object_list = Tokuten_post.objects.all()
        context['object_list'] = object_list
        return context

class TokutenView(CreateView):
    form_class = TokutenForm
    template_name = "tokuten.html"
    success_url = reverse_lazy('oharaapp:post_success')
    
    def form_valid(self, form):
        # フォームデータを保存せずに取得
        post = form.save(commit=False)
        post.user = self.request.user  # 現在ログインしているユーザーを設定
        post.save()  # 保存
        return super().form_valid(form)  # その後、成功の処理を実行

class Tokuten_post_List(ListView):
    template_name='detail.html'
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            Tokuten_post_list = Tokuten_post.objects.filter(
                subject__icontains=query
            )
        else:
            Tokuten_post_list = Tokuten_post.objects.all().order_by('posted_at')
        return Tokuten_post_list
    

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}login{% endblock %}
{% block page_title %}Login{% endblock page_title %}
{% block header_id %}header_login{% endblock %}
{% block contents %}
  <div class="form_login">
    <div class="container">
        {% if form.errors %}
          <p style='color: red'>ユーザー名とパスワードが一致しません。</p>
        {% endif %}
    
        <form method='post'>
          {% csrf_token %}
          <h2 class="login_text">Please Log in</h2>

          <label for="Username" class='visually-hidden'>User name</label>
          <input class="login_input"
                type="text"
                name='username'
                id='id_username'
                maxlength='150'
                {% comment %} 大文字使わない {% endcomment %}
                autocapitalize='none' 
                {% comment %} 名前自動入力 {% endcomment %}
                autocomplete='username'
                class='form-control'
                {% comment %} ヒントテキスト {% endcomment %}
                placeholder='ユーザー名'
                {% comment %} 必須項目化 {% endcomment %}
                required 
                {% comment %} 自動フォーカス {% endcomment %}
                autofocus>
          <br>
          <label for="Password" class='visually-hidden'>Password</label>
          <input  class="login_input login_input2"
                  type="password"
                  name='password'
                  id='id_password'
                  autocomplete='current-password'
                  class='form-control'
                  placeholder='パスワード'
                  required 
                  autofocus>
          <br>
          <input class="login_button button"
                  type='submit'
                  value='ログイン'>
        </form>
      </div>
  </div>
{% endblock %}

accounts/templates/logout.html
{% extends "base.html" %}
{% load static %}
{% block title %}Log out{% endblock %}
{% block page_title %}logout{% endblock page_title %}
{% block header_id %}header_logout{% endblock %}
{% block contents %}
    <div class="logout_text">
        <div class="container">
            <h3 class="logout_h3">ログアウトしました</h3>
            <p class="return_top"><a href="{% url 'oharaapp:index' %}">トップページへ</a></p>
        </div>
    </div> 
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sign up{% endblock %}
{% block page_title %}Sign up{% endblock page_title %}
{% block header_id %}header_signup{% endblock %}
{% block header_home_logo %}<li class="ohara_logo"><a href="{% url 'oharaapp:index' %}"><img src={% static "assets/img/大原アイコン-removebg-preview.png" %} alt="大原logo"></a></li>{% endblock %}
{% block contents %}
<div style="width: 480px; margin: auto;">
    <div class='container'>
        <div class='signup_div'>
            <form method='post'>
                {% csrf_token %}
                {% for field in form %}
                    <p class='signup_box'>
                        {{ field.label_tag }}<br>
                        {{ field }}
                        {% if field.help_text %}
                            <p class="signup_help_text"><small style='color: grey'>{{ field.help_text }}</small></p>
                        {% endif %}
                        {% for error in field.errors %}
                            <p class='signup_error_text' style='color: red'>{{ error }}</p>
                        {% endfor %}
                    </p>
                {% endfor %}
                <p class="signup_red_text" style='color:red'>
                    ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。
                </p>
                <input class='button_signup' type="submit" value='Sign up'>
            </form>
            <br>
            <p class='signup_return_index'>
                <a href="{% url 'oharaapp:index' %}">トップページに戻る</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/signup_success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}signup_success{% endblock %}
{% block page_title %}Sign up{% endblock page_title %}
{% block header_id %}header_signup_success{% endblock %}
{% block contents %}
    <div class="signup_success_div">
        <div class="container">
            <p class='signup_success_text'>登録が完了しました</p>
            <p class='signup_success_button button'><a href="{% url 'accounts:login' %}">ログインはこちらから</a></p>
        </div>
    </div>
{% endblock %}

oharaapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">        
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="授業で作成したサイト">
        <!-- lel=""	現在の文書から見たリンク先の関係 -->
        <link rel="icon" type="image/png" href={% static "assets/img/favicon.png" %}>

    <!--CSS-->
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link href="https://fonts.googleapis.com/css?family=Philosopher" rel="stylesheet">
        <link  href="{% static "css/styles.css" %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <div class="container">
                <div class="logo_header">
                    <a href="{% url 'oharaapp:index' %}">
                        <img src="{% static "assets/img/大原アイコン-removebg-preview.png" %}" alt="大原ロゴ" class="button">
                    </a>
                </div>            
                <nav class="menu_nav">
                    <ul class="list_menu">
                        {% if user.is_authenticated %}
                            <li class="button"><a href="{% url 'oharaapp:index' %}">HOME</a></li>
                            <li class="button">
                                <a href="{% url 'accounts:logout' %}" class="true_login_user_icon" onclick="event.preventDefault(); document.getElementById('logoutForm').submit();">ログアウト</a>
                                <form id="logoutForm" action="{% url 'accounts:logout' %}" method="POST">
                                    {% csrf_token %}
                                </form>
                            </li>
                        {% else %}
                            <li><a href="{% url 'oharaapp:index' %}">HOME</a></li>
                        {% endif %}
                    </ul>
                </nav> 
            </div>
        </header>
        <main>
            <div class="main_view">
                <div class="container">
                    <p class="page_title">{% block page_title %}{% endblock %}</p>
                </div>
            </div>
            <!-- メインエリア部分 -->
            {% block contents %}{% endblock %}
        </main>
        <footer>
            <div class="wrapper">
                <div class="container">
                    <p><small>&copy; 2024 sono_ohara</small></p>
                </div>
            </div>
        </footer>
    </body>
</html>

oharaapp/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}検索{% endblock %}
{% block page_title %}~点数一覧＆検索~{% endblock %}
{% block header_id %}header_toukuten{% endblock %} 
{% block contents %}
    <div class="toukuten_form">
        <div class="container">
            <form method="GET">
                <input type="text" name="query" class="post_text" placeholder="検索する">
                <button type="submit">🔍</button>
            </form>
            <p class="sub-title">※科目別に点数を検索することができます。</p>
        </div>
    </div>        <!-- 投稿一覧 -->
    <div class="post_div">
        <div class="container">
            <p class="post_detail_p">~科目＆点数一覧~</p>
            {% if posts %}
                <ul>
                    {% for post in posts %}
                        <li class="post_detail">
                            <h4>科目: {{ post.subject }}</h4>
                            <p>点数: {{ post.num }}点</p>
                            <small>投稿日時: {{ post.posted_at }} 投稿者: {{ post.user.username }}</small>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>現在、掲示板には投稿がありません。</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

oharaapp/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}得点管理{% endblock %}
{% block page_title %}得点管理{% endblock page_title %}
{% block header_id %}header_index{% endblock %}
{% block contents %}

    <div class="index_main_div">
        <div class="container">
            <p><span>❁</span>このアプリは点数を入力して管理することができます。
                <br><span>❁</span>入力する際は「科目名」と「点数」を入力してください。
            </p>
            {% if user.is_authenticated %}
                <div class="index_button_flex">
                    <li class="button"><a href="{% url 'oharaapp:mypage' %}" class="button_index">マイページ</a></li>
                    <li class="button"><a href="{% url 'oharaapp:tokuten' %}" class="button_index">点数を入力</a></li>
                    <li class="button"><a href="{% url 'oharaapp:detail' %}" class="button_index">検索</a></li>
                </div>
            {% else %}
                <div class="else_login_button">
                    <li class="button"><a href="{% url 'accounts:signup' %}">サインアップ</a></li>
                    <li class="button"><a href="{% url 'accounts:login' %}">ログイン</a></li>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

oharaapp/templates/mypage.html
{% extends "base.html" %}
{% load static %}
{% block title %}大原News{% endblock %}
{% block page_title %}得点管理{% endblock page_title %}
{% block header_id %}header_index{% endblock %}
{% block contents %}
    <div class="mypage_main_div">
        <div class="container">
            <p>{{ user }}さんの点数一覧</p>
            {% for item in object_list %}
                {% if user == item.user %}
                    <div class="mypage_sub_div">【科目】: {{item.subject}}【点数】: {{item.num}}点</div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

oharaapp/templates/post_success.html
{% extends "base.html" %}
{% load static %}
{% block title %}入力完了{% endblock %}
{% block page_title %}入力完了{% endblock %}
{% block header_id %}header_toukuten{% endblock %} 
{% block contents %}
    <div class="post_success_div">
        <div class="container">
            <p class="sucess_text_p">点数の登録が完了しました。</p>
            <div class="post_flex">
                <li class="button"><a href="{% url 'oharaapp:index' %}">HOMEに戻る</a></li>
                <li class="button"><a href="{% url 'oharaapp:tokuten' %}">入力を続ける</a></li>
            </div>
        </div>
    </div>
    
{% endblock %}

oharaapp/templates/tokuten.html
{% extends "base.html" %}
{% load static %}
{% block title %}得点入力{% endblock %}
{% block page_title %}得点入力{% endblock page_title %}
{% block header_id %}header_tokuten{% endblock %}

{% block contents %}
    <div class="tokuten_main_div">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                科目 {{form.subject}}
                <br>
                点数 {{form.num}}
                <button type="submit" class="tokuten_button button">登録</button>
            </form>
        </div>
    </div>


{% endblock%}